name: Java CI

on: [push]

jobs:
   buildJar:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v1

         - name: Set up JDK 17
           uses: actions/setup-java@v1
           with:
              java-version: 17

         - name: Setup Gradle
           uses: gradle/actions/setup-gradle@v4

         - name: Build plugin jar
           run: ./gradlew jar

         - name: Run tests
           run: ./gradlew test

         - name: Upload built jar file
           uses: actions/upload-artifact@v4
           with:
              name: ${{ github.event.repository.name }}-test
              path: build/libs/${{ github.event.repository.name }}.jar

         - name: Upload test report
           if: always() # ensures this runs even if tests fail
           uses: actions/upload-artifact@v4
           with:
              name: test-report
              path: build/reports/tests/test/

         - name: Deploy test report to GitHub Pages
           if: success() || failure() # run this even if tests fail
           uses: peaceiris/actions-gh-pages@v3
           with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: build/reports/tests/test
              publish_branch: gh-pages

         - uses: "marvinpinto/action-automatic-releases@latest"
           with:
              repo_token: "${{ secrets.GITHUB_TOKEN }}"
              automatic_release_tag: "latest"
              prerelease: false
              title: "Release"
              files: |
                 build/libs/${{ github.event.repository.name }}.jar
